CHK-6253: Added additional logging PaymentBoosterConfigProvider.php and added r…
bold-commerce/adobe-commerce-bold-checkout-payment-booster pull request #107
Opened 2024-10-31 16:15 UTC by DanielNordstrom

…eplace section to composer.json

2024-10-31 16:18 UTC, davemacaulay submitted a review, later dismissed

2024-10-31 20:20 UTC, JosephLeedy requested changes

2024-10-31 20:20 UTC, JosephLeedy commented on UI/PaymentBoosterConfigProvider.php
> +            if ($epsGatewayId === null) $errorMsgs[] = '$epsGatewayId is null.';
For readability, please use full `if` statements rather than short ones.

2024-11-01 15:52 UTC, davemacaulay approved these changes

2024-11-01 17:55 UTC, merged