CHK-4029: Add onboarding banner.
bold-commerce/adobe-commerce-bold-checkout-payment-booster pull request #61
Opened 2024-09-06 16:16 UTC by boldcaitlin

When Payment Booster is not enabled:
![image](https://github.com/user-attachments/assets/26c21efc-47a5-4e62-a0eb-40e4d5b8f22c)

When Payment Booster is enabled:
![image](https://github.com/user-attachments/assets/d99da314-0cf5-4139-a733-7162ab40e9a0)

2024-09-06 17:01 UTC, JosephLeedy requested changes

2024-09-06 17:01 UTC, JosephLeedy commented on view/adminhtml/web/css/onboard-styles.css
This should be a LESS stylesheet rather than plain CSS.

2024-09-09 15:07 UTC, boldcaitlin commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +        <css src="Bold_CheckoutPaymentBooster::css/onboard-styles.css"/>
I time boxed this to just over half a day and don’t have the svg rendering as expected. 

As neither of us could find sufficient Adobe Commerce docs, this follows patterns established in other [bold modules](https://github.com/bold-commerce/adobe-commerce-bold-checkout/tree/main/view/adminhtml/web/css) & [adobe documentation](https://developer.adobe.com/commerce/frontend-core/guide/css/themes/) I’d like to leave this styling as is - any objections?

2024-09-09 15:30 UTC, JosephLeedy commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +        <css src="Bold_CheckoutPaymentBooster::css/onboard-styles.css"/>
IMHO, our modules are doing it wrong. Let me play with this for an hour or two and see if I can get it to work the right way.

2024-09-09 22:18 UTC, JosephLeedy commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +        <css src="Bold_CheckoutPaymentBooster::css/onboard-styles.css"/>
I had inline the SVG files with the style rules due to an apparent bug in Magento's LESS parser.

2024-09-10 13:44 UTC, TimeBones approved these changes

2024-09-10 13:53 UTC, JosephLeedy commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +        <css src="Bold_CheckoutPaymentBooster::css/onboard-styles.css"/>
That's not necessary. Static content only needs to be deploying in production mode, and doing so if needed is a normal part of the installation process.

2024-09-10 13:59 UTC, JosephLeedy approved these changes

2024-09-10 14:02 UTC, boldcaitlin commented on view/adminhtml/layout/adminhtml_system_config_edit.xml
> +        <css src="Bold_CheckoutPaymentBooster::css/onboard-styles.css"/>
Even better! Thanks for confirming!

2024-09-10 14:04 UTC, merged

2024-09-10 17:10 UTC, JosephLeedy commented
For future reference, the solution for the issue with the images is that `onboard-styles.less` should have been prefixed with an underscore (i.e. `_onboard-styles.less`), the import in `_module.less` needs an extension, and the `url` rule should look like this: `url('@{baseDir}Bold_CheckoutPaymentBooster/images/file.svg')`.