As a brand with Braintree Wallet pays enabled, I am a offered these w…
bold-commerce/adobe-commerce-bold-checkout-payment-booster pull request #99
Opened 2024-10-23 13:42 UTC by NickolasMalovanets

…allet pays at the payment step.

2024-10-23 14:47 UTC, JosephLeedy requested changes

2024-10-24 13:54 UTC, NickolasMalovanets commented on view/frontend/web/js/action/express-pay/place-order-action.js
> +            }
Done

2024-10-24 14:25 UTC, nicolenorman approved these changes

2024-10-24 16:27 UTC, JosephLeedy submitted a review, later dismissed

2024-10-25 14:28 UTC, nicolenorman approved these changes

2024-10-29 14:22 UTC, nicolenorman commented on view/frontend/web/js/model/spi.js
> +            //await loadScriptAction('bold_braintree_fastlane', 'braintree.fastlane');
Is this intended to be left in and commented out?

2024-10-29 14:25 UTC, nicolenorman approved these changes

2024-10-29 14:31 UTC, nicolenorman approved these changes

2024-10-29 14:35 UTC, JosephLeedy approved these changes

2024-10-29 14:54 UTC, merged